# This environment includes all the required packages for this repo including running the test suite.
name: leafwax
channels:
  - default
  - conda-forge
dependencies:
  - python=3.12.9
  - pip
  - pytest
  - numpy
  - pandas
#  - pip:
#    - '-e .'
